### ISSUE TITLE
Add binary data translation support

### ISSUE THREAD

**Issue by MSeal** [nteract/scrapbook#15]
Determine the best ways to support binary data or various forms.

base64 encode in document, or arrow external store, etc

**Comment by rgbkrk** [comment]
I'm definitely a fan of a media type that contains a reference that (visual) frontends can resolve.

```js
  "application/vnd.nteract.scrapbook+json": {
    "ref": "s3://somewhere"
  }
```

**Comment by MSeal** [comment]
This was done for the pandas dataframe translation support
