### ISSUE TITLE
Should snaps and scraps combine?

### ISSUE THREAD

**Issue by MSeal** [nteract/scrapbook#19]
Today we had sketch saving snaps and glue saving scraps (see readme for detailed differences). I was thinking that the saved concepts could all be scraps while the glue and sketch methods determine the metadata associated with a scrap to indicate if it should be rendered or not.

This would require some careful functions for backwards compatibility with record methods as they were separated in papermill, but that doesn't mean we have to keep to the abstraction here.

Thoughts?

**Comment by rgbkrk** [comment]
If I recall correctly, the reason we had them separate was so that you could both record values that weren't displayed (to pull, e.g. an rmse value) and also display a plot that would be able to be surfaced.
