### ISSUE TITLE
Is this package already a replacement for `pm.record`?

### ISSUE THREAD

**Issue by choldgraf** [nteract/scrapbook#26]
Just wondering if I should give this a whirl, or if it's still WIP :-)

**Comment by MSeal** [comment]
Beta `pip install scrapbook-beta` for another week or two.
The only pending change is to merge `sketch` with `glue` as it was confusing early users.

**Comment by choldgraf** [comment]
cool, I just realized I probably should have asked this in a slack instead of creating an issue, sorry about that :-)

**Comment by MSeal** [comment]
Np -- not everyone is in slack so it's fine to ask here too :)

**Comment by rgbkrk** [comment]
On the plus side, this is now indexable by search engines and find-able by me 23 hours later!

**Comment by choldgraf** [comment]
hehehe \o/
