### ISSUE TITLE
Not being able to access parameters when load the whole directory

### ISSUE THREAD

**Issue by tqa236** [nteract/scrapbook#47]
Hello, I just use papermill and scrapbook recently and they are fantastic. I have a small issue now and I'm sorry if it's a little naive.

When I load a single notebook with scrapbook, I can access the parameters I use for papermill

```python
import scrapbook as sb
nbs = sb.read_notebook(path/to/notebook)
nbs.parameters
```

However, when I load all the notebooks from a directory, I can not find where is the parameters for each notebook.
book = sb.read_notebooks('result/')
```python
book = sb.read_notebooks(directory/to/notebooks)
```

Can I know how to access the parameters of each notebook in the latter case?

**Comment by MSeal** [comment]
Looks like we don't have that method defined on the Scrapbook collection. You could emulate the scraps behavior with `merge_dicts(nb.parameters for nb in sb.notebooks)` or `OrderedDict([(key, nb.parameters ) for key, nb in sb._notebooks.items()])`.

Would be an easy feature to add if you wanted to :)

**Comment by tqa236** [comment]
Thank you very much. I'm able to do that now. This code can access the scraps and the parameters at the same time:

```python
for scraps, nb in zip(book.notebook_scraps, book.notebooks):
    print(scraps)
    print(nb.parameters)
```
