### ISSUE TITLE
Error message: Mime type unknown is not currently supported

### ISSUE THREAD

**Issue by riyadparvez** [nteract/scrapbook#69]
I am trying the scrapbook tutorial.

```python
import scrapbook as sb

sb.glue("hello", "world")
sb.glue("number", 123)
sb.glue("some_list", [1, 3, 5])
sb.glue("some_dict", {"a": 1, "b": 2})
```
This is the output I see

> Mime type unknown is not currently supported.
> Mime type unknown is not currently supported.
> Mime type unknown is not currently supported.
> Mime type unknown is not currently supported.

**Comment by riyadparvez** [comment]
Can't reproduce in jupyterlab. I am using VS code jupyter extension to run the notebook. It probably has to do something with VS code jupyter extension.

**Comment by MSeal** [comment]
Those messages are mostly harmless, VSCode is trying to render the glue'd scraps and doesn't have  a renderer for the media type it saves as. Jupyterlab recognizes and skip rendering anything for scraps from scrapbook.

**Comment by plwalsh** [comment]
Has this issue come back? I'm using the latest pre-release version of vscode-jupyter and currently seeing this message under all my `sb.glue()` calls:

> No renderer could be found for mimetype "application/scrapbook.scrap.pandas+json", but one might be available on the Marketplace.

With a button beneath to "Search Marketplace". It's harmless, yes, but quite distracting.

**Comment by plwalsh** [comment]
@MSeal Has this issue come back? I'm using the latest pre-release version of vscode-jupyter and currently seeing this message under all my `sb.glue()` calls:

> No renderer could be found for mimetype "application/scrapbook.scrap.pandas+json", but one might be available on the Marketplace.

With a button beneath to "Search Marketplace". It's harmless, yes, but quite distracting.

**Comment by MSeal** [comment]
We've not made changes to scrapbook to this end, you may want to raise it with the vscode-jupyter repo to add a rule to silent render this mimetype as there's not a lot that can be done on the scrapbook side with the approach it takes.
