### ISSUE TITLE
Highlight demo fails on Binder with KeyError: "kernel_manager_class"

### ISSUE THREAD

**Issue by nealmcb** [nteract/scrapbook#75]
When I run the [highlight demo on binder](https://mybinder.org/v2/gh/nteract/scrapbook/master?filepath=binder%2Freglue_highlight_dates.ipynb) I get this error in the third cell:

```
In [3]:  pm.execute_notebook('./highlight_dates.ipynb', './outcomes/highlight_dates_run_one.ipynb', new_dates_one);

Executing: 0%
0/13 [00:00<?, ?cell/s]

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/srv/conda/envs/notebook/lib/python3.7/site-packages/traitlets/traitlets.py in get(self, obj, cls)
    527         try:
--> 528             value = obj._trait_values[self.name]
    529         except KeyError:

KeyError: 'kernel_manager_class'
```

During handling of the above exception, another exception occurred:

```
...
ImportError: cannot import name 'AsyncKernelManager' from 'jupyter_client' (/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyter_client/__init__.py)
```

**Comment by MSeal** [comment]
Thanks for raising.

That looks like an older version of jupyter_client is being loaded by conda forge when it's resolving dependencies instead of using the pip dependencies listed :/

@choldgraf do you happen to know if something changed or if out binder setup here is incorrect? It's not pulling the 6.x jupyter_client transient dependency.

**Comment by choldgraf** [comment]
Hmmm - so a couple things:

* first, there is a `binder/` folder in this repo, so anything in there will supercede anything else. the `requirements.txt` file in there doesn't list jupyter_client (https://github.com/nteract/scrapbook/blob/master/binder/requirements.txt)
* second, the `install_requires` of scrapbook [does exist](https://github.com/nteract/scrapbook/blob/master/setup.py#L66), but also doesn't seem to list `jupyter_client>6` in the [package requirements.txt](https://github.com/nteract/scrapbook/blob/master/requirements.txt).

Could we try adding `jupyter_client>6` to the root `requirements.txt` and see if that fixes it?

**Comment by MSeal** [comment]
We could do the >6, but shouldn't the transient dependencies pick up the latest version?

**Comment by choldgraf** [comment]
hmmm, my guess is that repo2docker pins jupyter_client in the default environment, and then when this package doesn't explicitly say it needs a newer version, it isn't upgraded

**Comment by MSeal** [comment]
Ok got it, I'll bump that to see if it fixes. Thanks for the insights

**Comment by willingc** [comment]
Just tested this. It seems resolved so I am closing.
