### ISSUE TITLE
Python 3.9 compatibility

### ISSUE THREAD

**Issue by mgasner** [nteract/scrapbook#78]
Hi y'all, just opening this as a tracking task -- at the moment, nteract-scrapbook is not Python 3.9 compatible, because of the dependency on pyarrow (https://github.com/apache/arrow/pull/8386).

**Comment by mgasner** [comment]
Hmm, I am having trouble reproducing this

**Comment by captainsafia** [comment]
@mgasner Thanks for the heads up!

**Comment by willingc** [comment]
@mgasner Our tests are passing on Python 3.9 now. 

Was this issue related to pyarrow where it was several months ago with 3.9 and we can close the issue now? 

If that wasn't the case, please add a bit more info on what the incompatibility is. Thank!

**Comment by mgasner** [comment]
Yes I believe so! Thank you!
