### ISSUE TITLE
All old versions have been dropped from pypi?

### ISSUE THREAD

**Issue by dciborow** [nteract/scrapbook#79]
I noticed a new release went out today. Was it intended that all old versions were removed from pypi? My scripts started breaking that I can't find version 0.2.0. 

I am going to try and update to the newest version. It was just a surprising break.

![image](https://user-images.githubusercontent.com/9027725/103819212-fa700200-5037-11eb-9217-794ac5bac07d.png)

**Comment by MSeal** [comment]
@dciborow No the old releases are still present under the old package name `nteract-scrapbook` -- we got permissions to take over the `scrapbook` package name and the 0.5.0 release is just a package rename with no feature changes. If you need the old versions use `nteract-scrapbook==0.2.0` and it will continue to work.

**Comment by MSeal** [comment]
If you were using the "scrapbook" pypi dependency from before the transition that package is no longer available and hasn't been maintained for several years now. We had reached out to the publisher over the course of two years try to contact them and the project was deemed abandoned.

**Comment by MSeal** [comment]
For as long as that package is sitting on github: https://github.com/odoku/Scrapbook you should be able to install directly by using `pip install git+https://github.com/odoku/Scrapbook.git#egg=scrapbook==0.2.0`

**Comment by dciborow** [comment]
I think that i never wanted scrapbook==0.2.0 in the first place!

Looks like my team got confused with our own deps.
